spring.datasource.url=jdbc:mysql://${DB_URL}:3306/${DB}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${SPRING_PORT}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=${MAIL_USERNAME}
app.mail.from-name=DriveSense

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# APIs
google.api.key=${GOOGLE_GEOLOCATOR_API_KEY}